
TYPE
	Machine_typ : 	STRUCT 
		operation : MACHINE_OPERATIONS_ENUM;
		_previousOperation : MACHINE_OPERATIONS_ENUM;
	END_STRUCT;
	MACHINE_OPERATIONS_ENUM : 
		(
		MACH_OP_NONE,
		MACH_OP_START_DISTRIBUTION,
		MACH_OP_ABORT_DISTRIBUTION
		);
	SYSTEM_GENERAL_STATUS_ENUM : 
		(
		PRINT_JOB_MANAGER_ERROR,
		BUILD_DISTRIBUTOR_ERROR,
		VFLCR_ERROR
		);
END_TYPE
