
TYPE
	Machine_typ : 	STRUCT 
		operation : MACHINE_OPERATIONS_ENUM;
		_previousOperation : MACHINE_OPERATIONS_ENUM;
	END_STRUCT;
	MACHINE_OPERATIONS_ENUM : 
		(
		MACH_OP_NONE,
		MACH_OP_CALIBRATE_LASER,
		MACH_OP_CALIBRATE_BEAM
		);
	SYSTEM_GENERAL_STATUS_ENUM : 
		(
		VFLCR_ERROR
		);
END_TYPE
